# Generated by Django 4.2.16 on 2024-10-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msysordering", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
