# Generated by Django 5.0.2 on 2024-09-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=300)),
                ('lname', models.CharField(max_length=300)),
                ('phonenum', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('add1', models.CharField(max_length=300)),
                ('add2', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('region', models.CharField(max_length=30)),
                ('zipc', models.CharField(max_length=10)),
            ],
        ),
    ]
