# Generated by Django 4.2.16 on 2024-09-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BalayBaler", "0003_product_remove_customer_created_at_cartitem_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(
                choices=[("100g", "100g"), ("4L", "4L"), ("6L", "6L")],
                default="100g",
                max_length=5,
            ),
        ),
    ]
