# Generated by Django 4.2.16 on 2024-09-17 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("BalayBaler", "0004_product_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[("100g", "100g"), ("1L", "1L"), ("6L", "6L")],
                        max_length=10,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="products/"),
        ),
        migrations.CreateModel(
            name="ProductSizeStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_level", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="BalayBaler.product",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="BalayBaler.size",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "size")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="available_sizes",
            field=models.ManyToManyField(
                through="BalayBaler.ProductSizeStock", to="BalayBaler.size"
            ),
        ),
    ]
