# Generated by Django 5.1.1 on 2024-10-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BalayBaler", "0006_remove_product_price_productsizestock_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-01-01 00:00:00"
            ),
            preserve_default=False,
        ),
    ]
