# Generated by Django 5.0.2 on 2024-11-19 13:37

import BalayBaler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BalayBaler', '0008_category_delete_customer_remove_cart_session_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_100g',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[BalayBaler.models.minValue]),
        ),
    ]
