# Generated by Django 5.0.2 on 2024-11-19 13:48

import BalayBaler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BalayBaler', '0009_alter_product_price_100g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_4L',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[BalayBaler.models.minValue]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_6L',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[BalayBaler.models.minValue]),
        ),
    ]
