# Generated by Django 5.0.2 on 2024-11-27 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BalayBaler', '0010_alter_product_price_4l_alter_product_price_6l'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('phnum', models.PositiveIntegerField(default=0)),
                ('email', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=10)),
                ('add1', models.CharField(max_length=100)),
                ('add2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=10)),
                ('zip', models.IntegerField(default=0)),
                ('delivery', models.IntegerField(default=100)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BalayBaler.cart')),
            ],
        ),
    ]
